baseURL = 'https://buggycode.netlify.app/'
languageCode = 'en-us'
title = 'Code Labs'

[module]
    [[module.imports]]
        path = "github.com/banditMukund/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params]

    [params.social]
      github = "payatu"
      twitter = "payatulabs"  

    [params.docs]
      prism = true
      themeColor = "red"
      title = "Code Labs"
      prismTheme = "lotusdocs"
      darkMode = true

    [params.flexsearch]
      enabled=false

             
    [params.footer]
            copyright = "© :YEAR: Buggy Codes by Payatu. Built with [**Lotus Docs**](https://github.com/colinwilson/lotusdocs)"
            version   = true # include git commit info in footer


# Permalinks
[permalinks]
  [permalinks.page]
    docs = '/labs/:sections[1]/:slug'
  [permalinks.section]
    docs = '/labs/:sections[1]'

